### ISSUE TITLE
Duplicated line in GIGS_lib_2210_VerticalCRS

### ISSUE THREAD

**Issue by desruisseaux** [IOGP-GIGS/GIGSTestDataset#1]
In the `GIGS_lib_2210_VerticalCRS` file, the following line appears twice:

https://github.com/IOGP-GIGS/GIGSTestDataset/blob/ffb2d1b062a00cbef4cc8b19f4a0d4c9f2cd167b/GIGSTestDatasetFiles/GIGS%202200%20Predefined%20Geodetic%20Data%20Objects%20test%20data/ASCII/GIGS_lib_2210_VerticalCRS.txt#L26

**Comment by gigsadmin** [comment]
Duplicate removed in v2.1 release, thanks Martin.
