### ISSUE TITLE
Incorrect entries in GIGS_3207 Test

### ISSUE THREAD

**Issue by michaelarnesonint** [IOGP-GIGS/GIGSTestDataset#2]
The conversion codes 61002 and 61022 in the test file GIGSTestDatasetFiles\GIGS 3200 User-defined Geodetic Data Objects test data\ASCII\GIGS_user_3207_ProjectedCRS.txt  should be 65002 and 65022.

**Comment by gigsadmin** [comment]
Corrected, thanks Michael
