### ISSUE TITLE
GIGS parameters value differ slightly from EPSG database

### ISSUE THREAD

**Issue by desruisseaux** [IOGP-GIGS/GIGSTestDataset#4]
The [GIGS_user_3206_Conversion.txt](https://github.com/IOGP-GIGS/GIGSTestDataset/blob/main/GIGSTestDatasetFiles/GIGS%203200%20User-defined%20Geodetic%20Data%20Objects%20test%20data/ASCII/GIGS_user_3206_Conversion.txt) file contains _scale factor_ parameter values set to 0.999601272. This value differ slightly from EPSG database, which defines 0.9996012717. See for example GIGS 65002 ("GIGS conversion 2"), where EPSG equivalence is [EPSG:19916 – British National Grid](https://epsg.org/conversion_19916/British-National-Grid.html). This is a difference of 3E-10, which is slightly more than the relative tolerance of 1E-10 recommended by GIGS tests (absolute tolerance after multiplication by parameter value is almost the same).

Possible actions that I see:
* Update the parameter value in GIGS tests.
* Or increase tolerance from 1E-10 to 3E-10.

**Comment by gigsadmin** [comment]
Thanks Martin, issue resolved in 2.1.2 version of file - have increased precision of value to match EPSG.
