### ISSUE TITLE
Ambiguous operation method names

### ISSUE THREAD

**Issue by desruisseaux** [IOGP-GIGS/GIGSTestDataset#5]
The following values in the _"EPSG Transformation Method Name"_ column of `GIGS_user_3208_CoordTfm.txt` are ambiguous:

* **"Geocentric translations"** is an alias for all the following methods in EPSG database:
  * Geocentric translations (geocentric domain)
  * Geocentric translations (geog2D domain) _— this is the method that seems to be used by GIGS tests_
  * Geocentric translations (geog3D domain)
* **"Position Vector 7-param. transformation"** is an alias for all the following methods in EPSG database:
  * Position Vector transformation (geocentric domain)
  * Position Vector transformation (geog2D domain) _— this is the method that seems to be used by GIGS tests_
  * Position Vector transformation (geog3D domain)
* **"Coordinate Frame rotation"** is an alias for all the following methods in EPSG database:
  * Coordinate Frame rotation (geocentric domain)
  * Coordinate Frame rotation (geog2D domain) _— this is the method that seems to be used by GIGS tests_
  * Coordinate Frame rotation (geog3D domain)
* **"Molodensky-Badekas 10-parameter transformation"** is an alias for all the following methods in EPSG database:
  * Molodensky-Badekas (CF geocentric domain)
  * Molodensky-Badekas (CF geog2D domain)
  * Molodensky-Badekas (CF geog3D domain)
  * Molodensky-Badekas (PV geocentric domain)
  * Molodensky-Badekas (PV geog2D domain)
  * Molodensky-Badekas (PV geog3D domain)

**Comment by gigsadmin** [comment]
Thanks Martin, issue fixed in 2.1.2 version of file with full unambigous names of operation methods/
